[server]
enableStaticServing = true
headless = true
runOnSave = false

[theme]
base = "light"
primaryColor = "#2563eb"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
textColor = "#0f172a"
font = "sans serif"

[client]
showSidebarNavigation = false

[browser]
gatherUsageStats = false
