[server]
enableStaticServing = true
headless = true
runOnSave = false

[theme]
base = "dark"
primaryColor = "#58a6ff"
backgroundColor = "#0d1117"
secondaryBackgroundColor = "#161b22"
textColor = "#e6edf3"

[client]
showSidebarNavigation = false

[browser]
gatherUsageStats = false
