command:
  - "streamlit"
  - "run"
  - "app.py"
  - "--server.port=8501"
  - "--server.enableStaticServing=true"

env:
  - name: SCM_CATALOG
    value: "supply_chain_management"
  - name: SCM_SCHEMA
    value: "main"

resources:
  memory: 2Gi
  cpu: "2"
